language: rust
dist: xenial
env:
    global:
        - PROJECT_NAME: ripgrep_all
        - RUST_BACKTRACE: full
addons:
    apt:
        packages:
            # For generating man page.
            - libxslt1-dev
            - asciidoc
            - docbook-xsl
            - xsltproc
            - libxml2-utils
            # Needed for completion-function test.
            - zsh
            # Needed for testing decompression search.
            - xz-utils
            - liblz4-tool
            # For building MUSL static builds on Linux.
            - musl-tools
            # rga specific
            - pandoc
            - poppler-utils
matrix:
    fast_finish: true
    include:
        # Nightly channel.
        # All *nix releases are done on the nightly channel to take advantage
        # of the regex library's multiple pattern SIMD search.
        - os: linux
          rust: nightly
          env: TARGET=x86_64-unknown-linux-musl
        - os: osx
          rust: nightly
          # XML_CATALOG_FILES is apparently necessary for asciidoc on macOS.
          env: TARGET=x86_64-apple-darwin XML_CATALOG_FILES=/usr/local/etc/xml/catalog
        - os: linux
          rust: stable
          env: TARGET=x86_64-unknown-linux-gnu
        - os: linux
          rust: stable
          env: TARGET=x86_64-unknown-linux-musl
        #- os: linux
        # rust: 1.35.0
        #  env: TARGET=arm-unknown-linux-gnueabihf GCC_VERSION=4.8
        #  addons:
        #    apt:
        #      packages:
        #        - gcc-4.8-arm-linux-gnueabihf
        #        - binutils-arm-linux-gnueabihf
        #        - libc6-armhf-cross
        #        - libc6-dev-armhf-cross
        #        # For generating man page.
        #        - libxslt1-dev
        #        - asciidoc
        #        - docbook-xsl
        #        - xsltproc
        #        - libxml2-utils
        - os: windows
          rust: nightly
          env: TARGET=x86_64-pc-windows-msvc
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
    provider: releases
    file_glob: true
    file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
    skip_cleanup: true
    on:
        condition: $TRAVIS_RUST_VERSION = nightly
        tags: true
    api_key:
        secure: BACN/S5fv590pb0bq7rUNX553yxrUDk3ZDcQ9JcG0DXFkv3/XIRzoc88YbDAp065Yk9DJ8SrT9X/Al9l8/MKoLfVmcz3jdFUJAsppkO4fouOxdtiufYq5MFFlrP6SYMHy7Gx95lZsh++NSwbq+1fjMkESOTWqz1ptUmAa7ERecGuX4t/4QoPfyTYNWb84LLDqeD9Geabj7HuCsjsa4gdJUFew13zvE1SFRUkVPVGo09j/+fYVZRoY0ObqHVYQEOlj4HtHHjaYnsLgKHcGGigc252N15sm7zFM0+/lRMYIx7LLv6SmFc/eHqHy8D9gHzUx1tEYnScuNEDDHSS7hXfKGyTrOPfENAqzWCIAftveUVI/+rWmMIOWDxzxt5s9P9k9c93GP7L2L/HJlEZfr0UKQhHfcv/uOaS48vhh4WyzybgBRLFcNwrGKSoHgJhGRHdnQbTc8JMNPBEoJKdtSosQk56ZievMg2rDxF/GArpLTTe58+kMrhFbK9bGBP0YcZjaLnIZuuRf2LZQFtT9gSPFuvXjhwDaz/5a3Gp+9ZIEF50Ad/nf2xKf/rwFaFFJ0RkPdw20TCuerasQUnbpDmZRYnJNrdVlYKIIxQ6dF+PqO8/4RJ1tRYaWk79G8fDVRWp/IfvtduLKqgh/mjNgefOc9qf0DoBVxK7LJx5CHHomkE=
branches:
    only:
        # Pushes and PR to the master branch
        - master
        - windows
        # Ruby regex to match tags. Required, or travis won't trigger deploys when
        # a new tag is pushed.
        - /^\d+\.\d+\.\d+.*$/
notifications:
    email:
        on_success: never
